# Generated by Django 3.0.3 on 2020-03-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XHacker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=255)),
                ('soft_desc1', models.TextField(blank=True, max_length=1500)),
                ('soft_desc2', models.TextField(blank=True, max_length=2000)),
                ('image1', models.ImageField(blank=True, upload_to='softwareImage')),
                ('image2', models.ImageField(blank=True, upload_to='softwareImage')),
                ('download_link', models.CharField(blank=True, max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
