# Generated by Django 3.0.3 on 2020-03-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XHacker', '0002_softwaremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaremodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
