# Generated by Django 3.0.3 on 2020-03-24 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XHacker', '0003_softwaremodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=300)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('posted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soft_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XHacker.SoftwareModel')),
            ],
        ),
    ]
