# Generated by Django 3.0.3 on 2020-03-24 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0004_auto_20200324_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 10, 14, 28, 75556)),
        ),
    ]
