# Generated by Django 3.0.3 on 2020-03-24 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0008_auto_20200324_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 21, 23, 11, 262754)),
        ),
    ]
